
# Please don't change this.
# This is to check if the config is up to date.
version-cfg: 5

# For change language use this check
# Available languages:
# en-US - English
# ru-RU - Russian
# Send me your language file.
lang: "en-US"

# Type name of your server.
# This name replaces {namesever}.
nameserver: "A Minecraft Server"

# Delay time before displaying a message.
# Can be useful when setting up alignment with other plugins.
# In seconds. Fractional numbers are available, for example:
# second-from-start: 2.5 #2.5 seconds
# If you set it to 0 then the plugin will have the HIGHEST priority.
# second-from-start: 0
# Values less than 0.05 have no meaning and are rounded down to 0.
second-from-start: 1

# If you need to restrict some groups
#  from displaying a message, use this:
# If:
# use-permission: true
# The message will be displayed for
#  players with permissions jmp.view
use-permission: false

# Support AuthMe
auth-me:
# If "true" then message will send after logging player
  send-message-after-logging: false

# Text when the player join.
# Here you can change text for join player
#  in your server.
# Placeholders available from PlaceholderAPI.
# Available placeholders (working without PAPI):
#  {player} - player nickname
#  {nameserver} - server name
#  {world-name} - world name
#  {world-time} - world time
#  {online} - number of online players
text:
  owner:
    - "§e◆ Welcome, §f{player}§e!"
    - "§e◆ It is welcome message for Owner!"
  vip:
    - "§e◆ Welcome, §f{player}§e!"
    - "§e◆ It is welcome message for Vip!"
  default:
    - "§e◆ Welcome, §f{player}§e!"
    - "§e◆ You have entered the server §f{nameserver}§e!"
    - "§e◆ Time in this world: §f{world-time}§e."
    - "§e◆ Players online: §f{online}§e."
    - "§e◆ Allow flight mode: §f%player_allow_flight%§e." #Use: /papi ecloud download Player