name: JoinMessagePlugin
version: 1.1.0-SNAPSHOT
api-version: '1.14'
main: org.JMP.plugin.Main
authors: [nekriS]
softdepend: [PlaceholderAPI, LuckPerms, AuthMe]
commands:
  jmp:
    description: Command of plugin
    usage: /jmp [reload|info|message|help]
    aliases:
      - joinmessageplugin