name: JoinMessagePlugin
version: 1.0.6-SNAPSHOT
api-version: 1.17
main: org.JMP.plugin.Main
softdepend: [PlaceholderAPI, LuckPerms, AuthMe]
commands:
  jmp:
    description: Command of plugin
    usage: /jmp <command>
    aliases:
      - joinmessageplugin